build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  win_arm64: win_arm64
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  triggers:
    - push
    - pull_request
provider:
  win_arm64: github_actions
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
test: native_and_emulated
